//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fib.Net.Core.Registry {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fib.Net.Core.Registry.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a single location header returned.
        /// </summary>
        internal static string BlobPusherRedirectLocationErrorMessage {
            get {
                return ResourceManager.GetString("BlobPusherRedirectLocationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find field &apos;schemaVersion&apos; in manifest.
        /// </summary>
        internal static string ManifestPullerMissingSchemaVersionExceptionMessage {
            get {
                return ResourceManager.GetString("ManifestPullerMissingSchemaVersionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifest was not a json object.
        /// </summary>
        internal static string ManifestPullerNotJsonExceptionMessage {
            get {
                return ResourceManager.GetString("ManifestPullerNotJsonExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `schemaVersion` field is not an integer.
        /// </summary>
        internal static string ManifestPullerSchemaVersionNotIntExceptionMessage {
            get {
                return ResourceManager.GetString("ManifestPullerSchemaVersionNotIntExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O error due to broken pipe: the server shut down the connection. Check the server log if possible. This could also be a proxy issue. For example, a proxy may prevent sending packets that are too large..
        /// </summary>
        internal static string RegistryBrokenPipeExceptionMessage {
            get {
                return ResourceManager.GetString("RegistryBrokenPipeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManifestPuller#handleResponse does not return null.
        /// </summary>
        internal static string RegistryClientManifestPullerReturnedNullExceptionMessage {
            get {
                return ResourceManager.GetString("RegistryClientManifestPullerReturnedNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry failed to respond.
        /// </summary>
        internal static string RegistryNoResponseExceptionMessage {
            get {
                return ResourceManager.GetString("RegistryNoResponseExceptionMessage", resourceCulture);
            }
        }
    }
}
