//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fib.Net.Core.Caching {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fib.Net.Core.Caching.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest found, but missing container configuration.
        /// </summary>
        internal static string CacheStorageReaderContainerConfigurationMissingExecpetionMessage {
            get {
                return ResourceManager.GetString("CacheStorageReaderContainerConfigurationMissingExecpetionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid schemaVersion in manifest: {0}
        ///1 and 2 are supported..
        /// </summary>
        internal static string CacheStorageReaderInvalidSchemaVersionExecpetionMessageFormat {
            get {
                return ResourceManager.GetString("CacheStorageReaderInvalidSchemaVersionExecpetionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found non-digest file in layers directory.
        /// </summary>
        internal static string CacheStorageReaderNonDigestFileExceptionMessage {
            get {
                return ResourceManager.GetString("CacheStorageReaderNonDigestFileExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest was not a json object.
        /// </summary>
        internal static string CacheStorageReaderNotJsonExecpetionMessage {
            get {
                return ResourceManager.GetString("CacheStorageReaderNotJsonExecpetionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find field &apos;schemaVersion&apos; in manifest.
        /// </summary>
        internal static string CacheStorageReaderSchemaVersionMissingExecpetionMessage {
            get {
                return ResourceManager.GetString("CacheStorageReaderSchemaVersionMissingExecpetionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown manifest mediaType: {0}.
        /// </summary>
        internal static string CacheStorageReaderUnknownMediaTypeExecpetionMessageFormat {
            get {
                return ResourceManager.GetString("CacheStorageReaderUnknownMediaTypeExecpetionMessageFormat", resourceCulture);
            }
        }
    }
}
